pipeline {
    agent {
        docker {
            image 'maven:3.6.3-jdk-11' 
            label 'slave'              
        }
    }
    stages {
        stage('Build') {
            steps {
                sh ''' if params.env=="dev"
                do echo "dev env is set"
                done
            }
        }
    }
}
