pipeline {
    agent {
        docker {
            image 'maven:3.6.3-jdk-11' 
            label 'slave'              
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'ls -la' 
            }
        }
    }
}
